// Models
import type { Lang } from "@/core/models/translations";

const EN = "program programmer programming progress project projector promise prompt proof property protect protocol prototype proxy process processor produce product profile profit compute computer compile compiler complete complex component compose compress common command comment commit community compare compass compatible data database date day debug decimal decode default define delete deliver demand deploy depth design detail develop device dictionary digital direct directory disk display distance document domain double download driver search second secure segment select semantic send sensor sentence sequence serial server service session set setting shape share shell shift short signal signature simple single size sketch slice socket software solid solve sort source space speed stack standard start state static status step storage store stream string structure style sum support switch symbol syntax system table tag target task template terminal test text thread time token tool topic total trace track traffic train transfer transform tree trie trigger true trust try tuple type";

const PT = "programa programação programador progresso projeto projetor promessa pronto prova propriedade proteger protocolo protótipo processo processador produzir produto perfil computar computador compilar compilador completo complexo componente compor comprimir comum comando comentário comunidade comparar compasso compatível dado dados data dia depurar decimal decodificar padrão definir deletar entregar demanda implantar profundidade desenho detalhe desenvolver dispositivo dicionário digital direto diretório disco distância documento domínio dobro driver busca buscar segundo seguro segmento selecionar semântica enviar sensor sentença sequência serial servidor serviço sessão conjunto configuração forma compartilhar terminal deslocar curto sinal assinatura simples único tamanho esboço fatia soquete software sólido resolver ordenar origem espaço velocidade pilha começar estado estático status passo armazenamento loja fluxo estrutura estilo soma suporte chave símbolo sintaxe sistema tabela tarefa modelo teste texto tempo ferramenta tópico total rastro rastrear tráfego treinar transferir transformar árvore trie gatilho verdadeiro tupla tipo caminho caminhão camada campo cancelar canal capa capacidade capítulo caractere carga carregar carta cartão casa caso causa célula centro certo chamada chamar ciclo";

// The autocomplete dictionaries, one per interface language, sorted and without duplicates.
export const WORDS: Record<Lang, string[]> = {
  en: [...new Set(EN.split(" "))].sort(),
  pt: [...new Set(PT.split(" "))].sort(),
};
