// Models
import type { Localized } from "../translations";
import type { VizKey } from "../viz";
import type { AlgorithmSpec, KpiSpec } from "./spec";

const SIZE = { sizeLabel: { en: "Walls", pt: "Paredes" }, minN: 10, maxN: 40, stepN: 5, defaultN: 28, shuffleLabel: { en: "New maze", pt: "Novo labirinto" }, stepMs: 110, family: "pathfinding", kind: "grid" } as const;

const LEGEND: [VizKey, Localized][] = [["vis", { en: "closed", pt: "fechado" }], ["primary", { en: "open", pt: "aberto" }], ["act", { en: "current", pt: "atual" }], ["violet", { en: "path", pt: "caminho" }], ["green", { en: "start / goal", pt: "início / destino" }]];

const KPI_EXPANDED: KpiSpec = { key: "expanded", label: { en: "EXPANDED", pt: "EXPANDIDAS" }, sub: { en: "closed cells", pt: "células fechadas" } };
const KPI_PATH: KpiSpec = { key: "path", unitKey: "pathUnit", label: { en: "PATH", pt: "CAMINHO" }, sub: { en: "length once the goal is reached", pt: "comprimento ao chegar" } };
const KPI_WALLS: KpiSpec = { key: "walls", label: { en: "WALLS", pt: "PAREDES" }, sub: { en: "of 880 cells blocked", pt: "de 880 células bloqueadas" } };

const CHART_TITLE = { en: "CELLS EXPANDED · 44×20 MAZE", pt: "CÉLULAS EXPANDIDAS · LABIRINTO 44×20" };
const CHART: [string, number, boolean?][] = [["bfs", 612], ["dijkstra", 604], ["bidirectional", 310], ["a*", 188], ["greedy", 96], ["jps", 41]];
const CHART_NOTE = { en: "same maze, same start and goal", pt: "mesmo labirinto, mesmo início e destino" };

const selfIn = (chart: [string, number, boolean?][], label: string): [string, number, boolean?][] => chart.map(([name, value]) => (name === label ? [name, value, true] : [name, value]));

const STAGE_PATH: [VizKey, Localized, Localized] = ["violet", { en: "path", pt: "caminho" }, { en: "follow parents back to the start", pt: "segue os pais até o início" }];

export const PATHFINDING_MORE = {
  greedy: {
    ...SIZE,
    slug: "greedy-best-first",
    name: "Greedy best-first",
    subtitle: { en: "heuristic only · no cost so far", pt: "só a heurística · sem custo até aqui" },
    tagline: { en: "greedy best-first · always toward the goal, whatever it costs", pt: "greedy best-first · sempre rumo ao destino, custe o que custar" },
    legend: LEGEND,
    kpis: [KPI_EXPANDED, { key: "open", label: { en: "OPEN SET", pt: "ABERTO" }, sub: { en: "candidates ranked by h", pt: "candidatas ordenadas por h" } }, { key: "pushed", label: { en: "PUSHES", pt: "INSERÇÕES" }, sub: { en: "cells added to the open set", pt: "células adicionadas ao aberto" } }, KPI_PATH, KPI_WALLS],
    idea: {
      en: [
        "Greedy best-first search ranks the open cells by the heuristic alone, the estimated distance to the goal, and ignores how far each one is from the start. It therefore runs straight at the goal, expanding very few cells when the way is clear.",
        "The price is the path. Because the cost so far is never considered, a cell reached by a long detour is as good as one reached directly, and the path it returns can be much longer than the shortest. It is A* with g dropped: fast, memory-light, and not optimal.",
      ],
      pt: [
        "A busca greedy best-first ordena as células abertas só pela heurística, a distância estimada ao destino, e ignora quão longe cada uma está do início. Por isso corre direto ao destino, expandindo pouquíssimas células quando o caminho está livre.",
        "O preço é o caminho. Como o custo até aqui nunca é considerado, uma célula alcançada por um desvio longo vale o mesmo que uma alcançada direto, e o caminho devolvido pode ser bem mais longo que o mínimo. É o A* sem o g: rápido, leve em memória, e não ótimo.",
      ],
    },
    stages: [["primary", { en: "pop", pt: "retira" }, { en: "the open cell closest to the goal by h", pt: "a célula aberta mais próxima do destino por h" }], ["act", { en: "check", pt: "checa" }, { en: "is it the goal? then rebuild", pt: "é o destino? então reconstrói" }], ["swap", { en: "push", pt: "insere" }, { en: "unvisited neighbours, ranked by h alone", pt: "vizinhos não visitados, ordenados só por h" }], STAGE_PATH],
    complexity: [
      [{ en: "best", pt: "melhor" }, "O(d)", "green", { en: "a clear line to the goal", pt: "linha livre até o destino" }],
      [{ en: "average", pt: "médio" }, "O(E log V)", "text", { en: "usually far fewer cells than A*", pt: "em geral bem menos células que o A*" }],
      [{ en: "worst", pt: "pior" }, "O(E log V)", "neg", { en: "a dead-end pocket facing the goal", pt: "um beco sem saída virado para o destino" }],
      [{ en: "space", pt: "espaço" }, "O(V)", "text", { en: "open set and parents", pt: "aberto e pais" }],
    ],
    chartTitle: CHART_TITLE,
    chart: selfIn(CHART, "greedy"),
    chartNote: { en: "greedy expanded the least and found a path 23% longer than the shortest", pt: "o greedy expandiu menos e achou um caminho 23% mais longo que o mínimo" },
    when: {
      en: ["Any path will do and speed matters: crowd simulation, rough routing before a refinement pass.", "Open terrain with few obstacles, where the heuristic is nearly exact."],
      pt: ["Qualquer caminho serve e a velocidade importa: simulação de multidões, rota grosseira antes de um refinamento.", "Terreno aberto com poucos obstáculos, em que a heurística é quase exata."],
    },
    pitfalls: {
      en: ["Not optimal: a U-shaped wall in front of the goal makes it explore the whole pocket and return a long path.", "It does not revisit: a cell reached the long way first keeps that parent forever.", "Weighting the heuristic in A* (f = g + w·h) gives a tunable middle ground; w → ∞ is greedy."],
      pt: ["Não é ótimo: uma parede em U na frente do destino faz explorar o bolsão inteiro e devolver um caminho longo.", "Não revisita: uma célula alcançada primeiro pelo caminho longo mantém esse pai para sempre.", "Ponderar a heurística no A* (f = g + w·h) dá um meio-termo ajustável; w → ∞ é o greedy."],
    },
    history: {
      en: "Best-first search with a heuristic goes back to Judea Pearl's 1984 book Heuristics, where greedy best-first is the simplest member of the family and A* the one with the optimality proof. Game programmers rediscover it every time a map is open enough that the detours do not show.",
      pt: "A busca best-first com heurística remonta ao livro Heuristics de Judea Pearl, de 1984, onde o greedy best-first é o membro mais simples da família e o A* o que tem a prova de otimalidade. Programadores de jogos o redescobrem toda vez que um mapa é aberto o bastante para os desvios não aparecerem.",
    },
    file: "greedy_best_first",
    code: {
      ts: ["function greedyBestFirst(grid: Grid, start: Cell, goal: Cell) {", "  const open = new MinHeap<Cell>([start]);", "  const seen = new Set([start]), parent = new Map();", "  while (open.size > 0) {", "    const current = open.pop(); // lowest heuristic, cost so far ignored", "    if (current === goal) return rebuild(parent, current);", "    for (const neighbor of neighbors(grid, current)) {", "      if (seen.has(neighbor)) continue;", "      seen.add(neighbor);", "      parent.set(neighbor, current);", "      open.push(neighbor, heuristic(neighbor, goal));", "    }", "  }", "  return null;", "}"],
      py: ["def greedy_best_first(grid, start, goal):", "    open_set = [(heuristic(start, goal), start)]", "    seen, parent = {start}, {}", "    while open_set:", "        _, current = heapq.heappop(open_set)  # lowest heuristic, cost so far ignored", "        if current == goal: return rebuild(parent, current)", "        for neighbor in neighbors(grid, current):", "            if neighbor in seen: continue", "            seen.add(neighbor)", "            parent[neighbor] = current", "            heapq.heappush(open_set, (heuristic(neighbor, goal), neighbor))", "", "", "    return None", ""],
      java: ["List<Cell> greedyBestFirst(Grid grid, Cell start, Cell goal) {", "  PriorityQueue<Cell> open = new PriorityQueue<>(byHeuristic); open.add(start);", "  Set<Cell> seen = new HashSet<>(Set.of(start)); Map<Cell,Cell> parent = new HashMap<>();", "  while (!open.isEmpty()) {", "    Cell current = open.poll(); // lowest heuristic, cost so far ignored", "    if (current.equals(goal)) return rebuild(parent, current);", "    for (Cell neighbor : neighbors(grid, current)) {", "      if (seen.contains(neighbor)) continue;", "      seen.add(neighbor);", "      parent.put(neighbor, current);", "      neighbor.score = heuristic(neighbor, goal); open.add(neighbor);", "    }", "  }", "  return null;", "}"],
      cpp: ["std::vector<Cell> greedyBestFirst(const Grid& grid, Cell start, Cell goal) {", "  std::priority_queue<Node, std::vector<Node>, ByScore> open; open.push({start, heuristic(start, goal)});", "  std::unordered_set<Cell> seen{start}; std::unordered_map<Cell,Cell> parent;", "  while (!open.empty()) {", "    Cell current = open.top().cell; open.pop(); // lowest heuristic, cost so far ignored", "    if (current == goal) return rebuild(parent, current);", "    for (Cell neighbor : neighbors(grid, current)) {", "      if (seen.count(neighbor)) continue;", "      seen.insert(neighbor);", "      parent[neighbor] = current;", "      open.push({neighbor, heuristic(neighbor, goal)});", "    }", "  }", "  return {};", "}"],
      c: ["Path greedy_best_first(Grid *grid, Cell start, Cell goal) {", "  Heap open = heap_new(); heap_push(&open, start, heuristic(start, goal));", "  bool seen[ROWS][COLS] = {0}; seen[start.row][start.col] = true; Cell parent[ROWS][COLS];", "  while (open.size > 0) {", "    Cell current = heap_pop(&open); /* lowest heuristic, cost so far ignored */", "    if (cell_eq(current, goal)) return rebuild(parent, current);", "    for (int direction = 0; direction < 4; direction++) { Cell neighbor = neighbor_at(grid, current, direction); if (!neighbor.ok) continue;", "      if (seen[neighbor.row][neighbor.col]) continue;", "      seen[neighbor.row][neighbor.col] = true;", "      parent[neighbor.row][neighbor.col] = current;", "      heap_push(&open, neighbor, heuristic(neighbor, goal));", "    }", "  }", "  return no_path();", "}"],
      go: ["func greedyBestFirst(grid Grid, start, goal Cell) []Cell {", "\topen := NewMinHeap(); open.Push(start, heuristic(start, goal))", "\tseen := map[Cell]bool{start: true}; parent := map[Cell]Cell{}", "\tfor open.Len() > 0 {", "\t\tcurrent := open.Pop() // lowest heuristic, cost so far ignored", "\t\tif current == goal { return rebuild(parent, current) }", "\t\tfor _, neighbor := range neighbors(grid, current) {", "\t\t\tif seen[neighbor] { continue }", "\t\t\tseen[neighbor] = true", "\t\t\tparent[neighbor] = current", "\t\t\topen.Push(neighbor, heuristic(neighbor, goal))", "\t\t}", "\t}", "\treturn nil", "}"],
      rs: ["fn greedy_best_first(grid: &Grid, start: Cell, goal: Cell) -> Option<Vec<Cell>> {", "    let mut open = BinaryHeap::new(); open.push(Reverse((heuristic(start, goal), start)));", "    let mut seen = HashSet::from([start]); let mut parent = HashMap::new();", "    while let Some(Reverse((_, current))) = open.pop() {", "        // popped the lowest heuristic, cost so far ignored", "        if current == goal { return Some(rebuild(&parent, current)); }", "        for neighbor in grid.neighbors(current) {", "            if seen.contains(&neighbor) { continue; }", "            seen.insert(neighbor);", "            parent.insert(neighbor, current);", "            open.push(Reverse((heuristic(neighbor, goal), neighbor)));", "        }", "    }", "    None", "}"],
    },
    pseudo: {
      en: ["GREEDY(start, goal)", "  open ← {start}; seen ← {start}", "  while open not empty", "    current ← the open cell with the lowest h(current, goal)", "    if current = goal: return path via parent", "    for each unseen neighbour of current: mark seen; parent[neighbour] ← current; add to open"],
      pt: ["GREEDY(início, destino)", "  aberto ← {início}; visto ← {início}", "  enquanto aberto não vazio", "    atual ← a célula aberta de menor h(atual, destino)", "    se atual = destino: retorna caminho pelos pais", "    para cada vizinho não visto de atual: marca visto; pai[vizinho] ← atual; adiciona ao aberto"],
    },
  },

  bidirectional: {
    ...SIZE,
    slug: "bidirectional-bfs",
    name: "Bidirectional BFS",
    subtitle: { en: "two frontiers that meet in the middle", pt: "duas fronteiras que se encontram no meio" },
    tagline: { en: "bidirectional BFS · two small circles instead of one big one", pt: "BFS bidirecional · dois círculos pequenos em vez de um grande" },
    legend: [["vis", { en: "closed", pt: "fechado" }], ["primary", { en: "both frontiers", pt: "as duas fronteiras" }], ["act", { en: "meeting cell", pt: "célula de encontro" }], ["violet", { en: "path", pt: "caminho" }], ["green", { en: "start / goal", pt: "início / destino" }]],
    kpis: [KPI_EXPANDED, { key: "front", label: { en: "FROM START", pt: "DO INÍCIO" }, sub: { en: "cells reached that side", pt: "células alcançadas desse lado" } }, { key: "back", label: { en: "FROM GOAL", pt: "DO DESTINO" }, sub: { en: "cells reached that side", pt: "células alcançadas desse lado" } }, { key: "rings", label: { en: "RINGS", pt: "ANÉIS" }, sub: { en: "one per turn, alternating", pt: "um por vez, alternando" } }, KPI_PATH],
    idea: {
      en: [
        "Bidirectional search runs two breadth-first searches at once, one from the start and one from the goal, growing one ring each in turn. The moment a cell is reached by both, the two parent chains join through it and form a shortest path.",
        "The saving comes from geometry. A single BFS to distance d fills a disc of about d² cells; two searches to distance d/2 fill two discs of (d/2)² each, half the area in total. On graphs with high branching the saving is exponential: b^(d/2) instead of b^d.",
      ],
      pt: [
        "A busca bidirecional roda duas buscas em largura ao mesmo tempo, uma do início e uma do destino, crescendo um anel cada por vez. No momento em que uma célula é alcançada pelas duas, as duas cadeias de pais se unem por ela e formam um caminho mínimo.",
        "A economia vem da geometria. Um BFS só até a distância d preenche um disco de cerca de d² células; duas buscas até d/2 preenchem dois discos de (d/2)² cada, metade da área no total. Em grafos com muita ramificação a economia é exponencial: b^(d/2) em vez de b^d.",
      ],
    },
    stages: [["primary", { en: "start ring", pt: "anel do início" }, { en: "one BFS layer from the start side", pt: "uma camada de BFS do lado do início" }], ["swap", { en: "goal ring", pt: "anel do destino" }, { en: "one BFS layer from the goal side", pt: "uma camada de BFS do lado do destino" }], ["act", { en: "meet", pt: "encontro" }, { en: "a cell reached from both sides", pt: "uma célula alcançada dos dois lados" }], ["violet", { en: "join", pt: "une" }, { en: "the two parent chains through it", pt: "as duas cadeias de pais por ela" }]],
    complexity: [
      [{ en: "best", pt: "melhor" }, "O(d)", "green", { en: "start and goal adjacent", pt: "início e destino vizinhos" }],
      [{ en: "average", pt: "médio" }, "O(b^(d/2))", "green", { en: "two half-depth searches", pt: "duas buscas de meia profundidade" }],
      [{ en: "worst", pt: "pior" }, "O(V + E)", "text", { en: "no path: both sides flood", pt: "sem caminho: os dois lados inundam" }],
      [{ en: "space", pt: "espaço" }, "O(b^(d/2))", "text", { en: "two frontiers, two parent maps", pt: "duas fronteiras, dois mapas de pais" }],
    ],
    chartTitle: CHART_TITLE,
    chart: selfIn(CHART, "bidirectional"),
    chartNote: CHART_NOTE,
    when: {
      en: ["Unweighted shortest paths between two known points: word ladders, social 'degrees of separation', puzzle states.", "Whenever both endpoints are known and the graph is large; on a map it halves BFS's work, on a state space it squares-roots it."],
      pt: ["Caminhos mínimos sem peso entre dois pontos conhecidos: escadas de palavras, 'graus de separação', estados de quebra-cabeça.", "Sempre que as duas pontas são conhecidas e o grafo é grande; num mapa divide o trabalho do BFS pela metade, num espaço de estados tira a raiz quadrada."],
    },
    pitfalls: {
      en: ["Stopping at the first meeting is only correct when the sides alternate ring by ring; expanding one side ahead can miss a shorter join.", "Directed graphs need the backward search to follow edges in reverse.", "With weights, use bidirectional Dijkstra and a careful stopping rule; the first meeting is not the shortest path."],
      pt: ["Parar no primeiro encontro só é correto quando os lados alternam anel por anel; adiantar um lado pode perder uma junção mais curta.", "Grafos direcionados precisam da busca de trás seguindo as arestas ao contrário.", "Com pesos, use Dijkstra bidirecional e uma regra de parada cuidadosa; o primeiro encontro não é o caminho mínimo."],
    },
    history: {
      en: "Ira Pohl analysed bidirectional search in his 1969 thesis and 1971 paper, and it has been standard in route planning ever since: contraction hierarchies and hub labels, the engines behind today's map services, run a bidirectional Dijkstra at their core.",
      pt: "Ira Pohl analisou a busca bidirecional na tese de 1969 e no artigo de 1971, e ela é padrão em planejamento de rotas desde então: hierarquias de contração e hub labels, os motores por trás dos mapas de hoje, rodam um Dijkstra bidirecional no núcleo.",
    },
    file: "bidirectional_bfs",
    code: {
      ts: ["function bidirectionalBfs(grid: Grid, start: Cell, goal: Cell) {", "  const front = { ring: [start], parent: new Map([[start, null]]) }, back = { ring: [goal], parent: new Map([[goal, null]]) };", "  while (front.ring.length > 0 && back.ring.length > 0) {", "    const meeting = expand(grid, front, back); // one ring from the start side", "    if (meeting) return join(front.parent, back.parent, meeting);", "    const met = expand(grid, back, front); // one ring from the goal side", "    if (met) return join(front.parent, back.parent, met);", "  }", "  return null;", "}", "function expand(grid: Grid, side: Side, other: Side) {", "  for (const current of side.ring.splice(0)) {", "    for (const neighbor of neighbors(grid, current)) {", "      if (side.parent.has(neighbor)) continue;", "      side.parent.set(neighbor, current); side.ring.push(neighbor);", "      if (other.parent.has(neighbor)) return neighbor;", "    }", "  }", "  return null;", "}"],
      py: ["def bidirectional_bfs(grid, start, goal):", "    front, back = Side([start], {start: None}), Side([goal], {goal: None})", "    while front.ring and back.ring:", "        meeting = expand(grid, front, back)  # one ring from the start side", "        if meeting: return join(front.parent, back.parent, meeting)", "        met = expand(grid, back, front)  # one ring from the goal side", "        if met: return join(front.parent, back.parent, met)", "", "    return None", "", "def expand(grid, side, other):", "    for current in side.take_ring():", "        for neighbor in neighbors(grid, current):", "            if neighbor in side.parent: continue", "            side.parent[neighbor] = current; side.ring.append(neighbor)", "            if neighbor in other.parent: return neighbor", "", "", "    return None", ""],
      java: ["List<Cell> bidirectionalBfs(Grid grid, Cell start, Cell goal) {", "  Side front = new Side(start), back = new Side(goal);", "  while (!front.ring.isEmpty() && !back.ring.isEmpty()) {", "    Cell meeting = expand(grid, front, back); // one ring from the start side", "    if (meeting != null) return join(front.parent, back.parent, meeting);", "    Cell met = expand(grid, back, front); // one ring from the goal side", "    if (met != null) return join(front.parent, back.parent, met);", "  }", "  return null;", "}", "Cell expand(Grid grid, Side side, Side other) {", "  for (Cell current : side.takeRing()) {", "    for (Cell neighbor : neighbors(grid, current)) {", "      if (side.parent.containsKey(neighbor)) continue;", "      side.parent.put(neighbor, current); side.ring.add(neighbor);", "      if (other.parent.containsKey(neighbor)) return neighbor;", "    }", "  }", "  return null;", "}"],
      cpp: ["std::vector<Cell> bidirectionalBfs(const Grid& grid, Cell start, Cell goal) {", "  Side front(start), back(goal);", "  while (!front.ring.empty() && !back.ring.empty()) {", "    if (auto meeting = expand(grid, front, back)) return join(front.parent, back.parent, *meeting); // start side", "    ", "    if (auto met = expand(grid, back, front)) return join(front.parent, back.parent, *met); // goal side", "    ", "  }", "  return {};", "}", "std::optional<Cell> expand(const Grid& grid, Side& side, Side& other) {", "  for (Cell current : side.takeRing()) {", "    for (Cell neighbor : neighbors(grid, current)) {", "      if (side.parent.count(neighbor)) continue;", "      side.parent[neighbor] = current; side.ring.push_back(neighbor);", "      if (other.parent.count(neighbor)) return neighbor;", "    }", "  }", "  return std::nullopt;", "}"],
      c: ["Path bidirectional_bfs(Grid *grid, Cell start, Cell goal) {", "  Side front = side_new(start), back = side_new(goal);", "  while (front.ring_size > 0 && back.ring_size > 0) {", "    Cell meeting = expand(grid, &front, &back); /* one ring from the start side */", "    if (meeting.ok) return join(&front, &back, meeting);", "    Cell met = expand(grid, &back, &front); /* one ring from the goal side */", "    if (met.ok) return join(&front, &back, met);", "  }", "  return no_path();", "}", "Cell expand(Grid *grid, Side *side, Side *other) {", "  Cell *ring = side_take_ring(side); for (int i = 0; ring[i].ok; i++) { Cell current = ring[i];", "    for (int direction = 0; direction < 4; direction++) { Cell neighbor = neighbor_at(grid, current, direction); if (!neighbor.ok) continue;", "      if (side_reached(side, neighbor)) continue;", "      side_set_parent(side, neighbor, current); side_push(side, neighbor);", "      if (side_reached(other, neighbor)) return neighbor;", "    }", "  }", "  return no_cell();", "}"],
      go: ["func bidirectionalBfs(grid Grid, start, goal Cell) []Cell {", "\tfront, back := newSide(start), newSide(goal)", "\tfor len(front.ring) > 0 && len(back.ring) > 0 {", "\t\tif meeting, ok := expand(grid, front, back); ok { // one ring from the start side", "\t\t\treturn join(front.parent, back.parent, meeting) }", "\t\tif met, ok := expand(grid, back, front); ok { // one ring from the goal side", "\t\t\treturn join(front.parent, back.parent, met) }", "\t}", "\treturn nil", "}", "func expand(grid Grid, side, other *Side) (Cell, bool) {", "\tfor _, current := range side.takeRing() {", "\t\tfor _, neighbor := range neighbors(grid, current) {", "\t\t\tif _, seen := side.parent[neighbor]; seen { continue }", "\t\t\tside.parent[neighbor] = current; side.ring = append(side.ring, neighbor)", "\t\t\tif _, met := other.parent[neighbor]; met { return neighbor, true }", "\t\t}", "\t}", "\treturn Cell{}, false", "}"],
      rs: ["fn bidirectional_bfs(grid: &Grid, start: Cell, goal: Cell) -> Option<Vec<Cell>> {", "    let (mut front, mut back) = (Side::new(start), Side::new(goal));", "    while !front.ring.is_empty() && !back.ring.is_empty() {", "        if let Some(meeting) = expand(grid, &mut front, &back) { // one ring from the start side", "            return Some(join(&front.parent, &back.parent, meeting)); }", "        if let Some(met) = expand(grid, &mut back, &front) { // one ring from the goal side", "            return Some(join(&front.parent, &back.parent, met)); }", "    }", "    None", "}", "fn expand(grid: &Grid, side: &mut Side, other: &Side) -> Option<Cell> {", "    for current in std::mem::take(&mut side.ring) {", "        for neighbor in grid.neighbors(current) {", "            if side.parent.contains_key(&neighbor) { continue; }", "            side.parent.insert(neighbor, current); side.ring.push(neighbor);", "            if other.parent.contains_key(&neighbor) { return Some(neighbor); }", "        }", "    }", "    None", "}"],
    },
    pseudo: {
      en: ["BIDIRECTIONALBFS(start, goal)", "  front ← BFS state from start; back ← BFS state from goal", "  repeat", "    grow front by one ring; if it touches a cell back has reached: join the two parent chains there", "    grow back by one ring; same check", "  until either side has no ring left: no path"],
      pt: ["BIDIRECTIONALBFS(início, destino)", "  frente ← estado de BFS do início; trás ← estado de BFS do destino", "  repete", "    cresce a frente um anel; se toca uma célula que trás já alcançou: une as duas cadeias de pais ali", "    cresce trás um anel; mesma checagem", "  até um lado ficar sem anel: sem caminho"],
    },
  },

  jps: {
    ...SIZE,
    slug: "jump-point-search",
    name: "Jump point search",
    subtitle: { en: "A* that skips straight runs", pt: "A* que pula os trechos retos" },
    tagline: { en: "JPS · on an open grid, only the corners matter", pt: "JPS · numa grade aberta, só as esquinas importam" },
    legend: [["vis", { en: "scanned while jumping", pt: "varrida no salto" }], ["primary", { en: "open jump point", pt: "ponto de salto aberto" }], ["act", { en: "current", pt: "atual" }], ["violet", { en: "path", pt: "caminho" }], ["green", { en: "start / goal", pt: "início / destino" }]],
    kpis: [{ key: "expanded", label: { en: "POPS", pt: "RETIRADAS" }, sub: { en: "jump points expanded", pt: "pontos de salto expandidos" } }, { key: "scanned", label: { en: "SCANNED", pt: "VARRIDAS" }, sub: { en: "cells passed while jumping", pt: "células percorridas nos saltos" } }, { key: "jumpPoints", label: { en: "JUMP POINTS", pt: "PONTOS DE SALTO" }, sub: { en: "found so far", pt: "encontrados até aqui" } }, { key: "open", label: { en: "OPEN SET", pt: "ABERTO" }, sub: { en: "jump points waiting", pt: "pontos de salto esperando" } }, KPI_PATH],
    idea: {
      en: [
        "On a uniform grid most of A*'s work is pointless: a cell in the middle of an open corridor has exactly one sensible successor, the next cell along. Jump point search keeps A*'s open set and heuristic, but instead of pushing every neighbour it jumps along a straight run and pushes only the cell where something changes: the goal, or a wall that forces a turn.",
        "Those cells are the jump points. Scanning a run costs a few cheap array reads, while each pushed cell costs a heap operation, so JPS expands ten to a hundred times fewer nodes than A* and returns the same optimal path. It needs no preprocessing and no extra memory, only a uniform-cost grid.",
      ],
      pt: [
        "Numa grade uniforme a maior parte do trabalho do A* é inútil: uma célula no meio de um corredor aberto tem exatamente um sucessor sensato, a próxima célula adiante. O jump point search mantém o conjunto aberto e a heurística do A*, mas em vez de inserir todo vizinho ele salta por um trecho reto e insere só a célula onde algo muda: o destino, ou uma parede que força uma curva.",
        "Essas células são os pontos de salto. Varrer um trecho custa algumas leituras baratas de vetor, enquanto cada célula inserida custa uma operação de heap, então o JPS expande de dez a cem vezes menos nós que o A* e devolve o mesmo caminho ótimo. Não precisa de pré-processamento nem memória extra, só de uma grade de custo uniforme.",
      ],
    },
    stages: [["primary", { en: "pop", pt: "retira" }, { en: "the jump point with the lowest g + h", pt: "o ponto de salto de menor g + h" }], ["vis", { en: "jump", pt: "salta" }, { en: "straight until a forced turn, the goal or a wall", pt: "em linha reta até uma curva forçada, o destino ou uma parede" }], ["swap", { en: "open", pt: "abre" }, { en: "the jump point found, with its distance", pt: "o ponto de salto encontrado, com sua distância" }], STAGE_PATH],
    complexity: [
      [{ en: "best", pt: "melhor" }, "O(d)", "green", { en: "a straight corridor to the goal: one jump", pt: "um corredor reto até o destino: um salto" }],
      [{ en: "average", pt: "médio" }, "O(E log V)", "green", { en: "same bound as A*, far fewer heap operations", pt: "mesmo limite do A*, bem menos operações de heap" }],
      [{ en: "worst", pt: "pior" }, "O(E log V)", "text", { en: "a maze of one-cell corridors: every cell is a jump point", pt: "um labirinto de corredores de uma célula: toda célula é ponto de salto" }],
      [{ en: "space", pt: "espaço" }, "O(V)", "text", { en: "the open set holds only jump points", pt: "o aberto guarda só pontos de salto" }],
    ],
    chartTitle: CHART_TITLE,
    chart: selfIn(CHART, "jps"),
    chartNote: { en: "pops for JPS · the scanned cells are cheap array reads", pt: "retiradas para o JPS · as células varridas são leituras baratas de vetor" },
    when: {
      en: ["Uniform-cost grids with open areas: real-time strategy games, tile maps, robot occupancy grids.", "When A* is too slow and there is no time to precompute anything."],
      pt: ["Grades de custo uniforme com áreas abertas: jogos de estratégia em tempo real, mapas de tiles, grades de ocupação de robôs.", "Quando o A* é lento demais e não há tempo de pré-calcular nada."],
    },
    pitfalls: {
      en: ["Weighted cells break it: a jump may skip over a cheaper detour. JPS is for uniform grids only.", "The 8-connected version has more pruning rules (diagonals) than the 4-connected one shown here; do not mix them.", "Narrow mazes turn every cell into a jump point and the gain disappears; measure before switching."],
      pt: ["Células com peso quebram o JPS: um salto pode pular um desvio mais barato. É só para grades uniformes.", "A versão de 8 vizinhos tem mais regras de poda (diagonais) que a de 4 mostrada aqui; não misture as duas.", "Labirintos estreitos transformam toda célula em ponto de salto e o ganho some; meça antes de trocar."],
    },
    history: {
      en: "Daniel Harabor and Alban Grastien presented jump point search in 2011 for 8-connected grids, and it became the reference for online grid pathfinding within a few years. JPS+ in 2014 precomputes the jump distances for another order of magnitude when the map is static.",
      pt: "Daniel Harabor e Alban Grastien apresentaram o jump point search em 2011 para grades de 8 vizinhos, e em poucos anos ele virou a referência de pathfinding online em grades. O JPS+ de 2014 pré-calcula as distâncias de salto para mais uma ordem de grandeza quando o mapa é estático.",
    },
    file: "jump_point_search",
    code: {
      ts: ["function jumpPointSearch(grid: Grid, start: Cell, goal: Cell) {", "  const open = new MinHeap<Cell>([start]), distance = new Map([[start, 0]]), parent = new Map();", "  while (open.size > 0) {", "    const current = open.pop(); // lowest distance + heuristic", "    if (current === goal) return rebuild(parent, current);", "    for (const direction of directionsFrom(current, parent.get(current))) {", "      const point = jump(grid, current, direction, goal);", "      if (point === null) continue;", "      const candidate = distance.get(current)! + manhattan(current, point);", "      if (candidate >= (distance.get(point) ?? Infinity)) continue;", "      distance.set(point, candidate); parent.set(point, current);", "      open.push(point, candidate + manhattan(point, goal));", "    }", "  }", "}", "function jump(grid: Grid, from: Cell, direction: Direction, goal: Cell): Cell | null {", "  const next = step(from, direction);", "  if (!walkable(grid, next)) return null;", "  if (next === goal || hasForcedNeighbor(grid, next, direction)) return next;", "  if (isVertical(direction)) for (const side of [LEFT, RIGHT]) if (jump(grid, next, side, goal)) return next;", "  return jump(grid, next, direction, goal);", "}"],
      py: ["def jump_point_search(grid, start, goal):", "    open_set = [(0, start)]; distance = {start: 0}; parent = {}", "    while open_set:", "        _, current = heapq.heappop(open_set)  # lowest distance + heuristic", "        if current == goal: return rebuild(parent, current)", "        for direction in directions_from(current, parent.get(current)):", "            point = jump(grid, current, direction, goal)", "            if point is None: continue", "            candidate = distance[current] + manhattan(current, point)", "            if candidate >= distance.get(point, math.inf): continue", "            distance[point] = candidate; parent[point] = current", "            heapq.heappush(open_set, (candidate + manhattan(point, goal), point))", "", "", "", "def jump(grid, start, direction, goal):", "    next_cell = step(start, direction)", "    if not walkable(grid, next_cell): return None", "    if next_cell == goal or has_forced_neighbor(grid, next_cell, direction): return next_cell", "    if is_vertical(direction) and any(jump(grid, next_cell, side, goal) for side in (LEFT, RIGHT)): return next_cell", "    return jump(grid, next_cell, direction, goal)", ""],
      java: ["List<Cell> jumpPointSearch(Grid grid, Cell start, Cell goal) {", "  PriorityQueue<Cell> open = new PriorityQueue<>(byScore); open.add(start); Map<Cell,Integer> distance = new HashMap<>(Map.of(start, 0)); Map<Cell,Cell> parent = new HashMap<>();", "  while (!open.isEmpty()) {", "    Cell current = open.poll(); // lowest distance + heuristic", "    if (current.equals(goal)) return rebuild(parent, current);", "    for (Direction direction : directionsFrom(current, parent.get(current))) {", "      Cell point = jump(grid, current, direction, goal);", "      if (point == null) continue;", "      int candidate = distance.get(current) + manhattan(current, point);", "      if (candidate >= distance.getOrDefault(point, Integer.MAX_VALUE)) continue;", "      distance.put(point, candidate); parent.put(point, current);", "      point.score = candidate + manhattan(point, goal); open.add(point);", "    }", "  }", "  return null; }", "Cell jump(Grid grid, Cell from, Direction direction, Cell goal) {", "  Cell next = step(from, direction);", "  if (!walkable(grid, next)) return null;", "  if (next.equals(goal) || hasForcedNeighbor(grid, next, direction)) return next;", "  if (direction.isVertical()) for (Direction side : List.of(LEFT, RIGHT)) if (jump(grid, next, side, goal) != null) return next;", "  return jump(grid, next, direction, goal);", "}"],
      cpp: ["std::vector<Cell> jumpPointSearch(const Grid& grid, Cell start, Cell goal) {", "  std::priority_queue<Node, std::vector<Node>, ByScore> open; open.push({start, 0}); std::unordered_map<Cell,int> distance{{start, 0}}; std::unordered_map<Cell,Cell> parent;", "  while (!open.empty()) {", "    Cell current = open.top().cell; open.pop(); // lowest distance + heuristic", "    if (current == goal) return rebuild(parent, current);", "    for (Direction direction : directionsFrom(current, parent)) {", "      std::optional<Cell> point = jump(grid, current, direction, goal);", "      if (!point) continue;", "      int candidate = distance[current] + manhattan(current, *point);", "      if (distance.count(*point) && candidate >= distance[*point]) continue;", "      distance[*point] = candidate; parent[*point] = current;", "      open.push({*point, candidate + manhattan(*point, goal)});", "    }", "  }", "  return {}; }", "std::optional<Cell> jump(const Grid& grid, Cell from, Direction direction, Cell goal) {", "  Cell next = step(from, direction);", "  if (!walkable(grid, next)) return std::nullopt;", "  if (next == goal || hasForcedNeighbor(grid, next, direction)) return next;", "  if (isVertical(direction)) for (Direction side : {LEFT, RIGHT}) if (jump(grid, next, side, goal)) return next;", "  return jump(grid, next, direction, goal);", "}"],
      c: ["Path jump_point_search(Grid *grid, Cell start, Cell goal) {", "  Heap open = heap_new(); heap_push(&open, start, 0); int distance[ROWS][COLS]; fill(distance, INF); distance[start.row][start.col] = 0; Cell parent[ROWS][COLS];", "  while (open.size > 0) {", "    Cell current = heap_pop(&open); /* lowest distance + heuristic */", "    if (cell_eq(current, goal)) return rebuild(parent, current);", "    for (int k = 0; k < direction_count(current, parent); k++) { Direction direction = directions_from(current, parent)[k];", "      Cell point = jump(grid, current, direction, goal);", "      if (!point.ok) continue;", "      int candidate = distance[current.row][current.col] + manhattan(current, point);", "      if (candidate >= distance[point.row][point.col]) continue;", "      distance[point.row][point.col] = candidate; parent[point.row][point.col] = current;", "      heap_push(&open, point, candidate + manhattan(point, goal));", "    }", "  }", "  return no_path(); }", "Cell jump(Grid *grid, Cell from, Direction direction, Cell goal) {", "  Cell next = step(from, direction);", "  if (!walkable(grid, next)) return no_cell();", "  if (cell_eq(next, goal) || has_forced_neighbor(grid, next, direction)) return next;", "  if (is_vertical(direction) && (jump(grid, next, LEFT, goal).ok || jump(grid, next, RIGHT, goal).ok)) return next;", "  return jump(grid, next, direction, goal);", "}"],
      go: ["func jumpPointSearch(grid Grid, start, goal Cell) []Cell {", "\topen := NewMinHeap(); open.Push(start, 0); distance := map[Cell]int{start: 0}; parent := map[Cell]Cell{}", "\tfor open.Len() > 0 {", "\t\tcurrent := open.Pop() // lowest distance + heuristic", "\t\tif current == goal { return rebuild(parent, current) }", "\t\tfor _, direction := range directionsFrom(current, parent) {", "\t\t\tpoint, ok := jump(grid, current, direction, goal)", "\t\t\tif !ok { continue }", "\t\t\tcandidate := distance[current] + manhattan(current, point)", "\t\t\tif old, seen := distance[point]; seen && candidate >= old { continue }", "\t\t\tdistance[point] = candidate; parent[point] = current", "\t\t\topen.Push(point, candidate+manhattan(point, goal))", "\t\t}", "\t}", "\treturn nil }", "func jump(grid Grid, from Cell, direction Direction, goal Cell) (Cell, bool) {", "\tnext := step(from, direction)", "\tif !walkable(grid, next) { return Cell{}, false }", "\tif next == goal || hasForcedNeighbor(grid, next, direction) { return next, true }", "\tif direction.vertical() { for _, side := range []Direction{left, right} { if _, ok := jump(grid, next, side, goal); ok { return next, true } } }", "\treturn jump(grid, next, direction, goal)", "}"],
      rs: ["fn jump_point_search(grid: &Grid, start: Cell, goal: Cell) -> Option<Vec<Cell>> {", "    let mut open = BinaryHeap::from([Reverse((0, start))]); let mut distance = HashMap::from([(start, 0)]); let mut parent = HashMap::new();", "    while let Some(Reverse((_, current))) = open.pop() {", "        // popped the lowest distance + heuristic", "        if current == goal { return Some(rebuild(&parent, current)); }", "        for direction in directions_from(current, parent.get(&current)) {", "            let Some(point) = jump(grid, current, direction, goal) else { continue };", "            ", "            let candidate = distance[&current] + manhattan(current, point);", "            if candidate >= *distance.get(&point).unwrap_or(&i32::MAX) { continue; }", "            distance.insert(point, candidate); parent.insert(point, current);", "            open.push(Reverse((candidate + manhattan(point, goal), point)));", "        }", "    }", "    None }", "fn jump(grid: &Grid, from: Cell, direction: Direction, goal: Cell) -> Option<Cell> {", "    let next = step(from, direction);", "    if !walkable(grid, next) { return None; }", "    if next == goal || has_forced_neighbor(grid, next, direction) { return Some(next); }", "    if direction.is_vertical() && [LEFT, RIGHT].iter().any(|&side| jump(grid, next, side, goal).is_some()) { return Some(next); }", "    jump(grid, next, direction, goal)", "}"],
    },
    pseudo: {
      en: ["JPS(start, goal)", "  A* over jump points: open ← {start}", "  pop the jump point with the lowest g + h; if it is the goal, rebuild the path", "  for each allowed direction: point ← JUMP(current, direction)", "    if point exists and g(current) + distance < g(point): update, push point", "JUMP(cell, direction): step once; stop at a wall (nothing), at the goal or at a forced turn (jump point); on a vertical run also try both sideways jumps; else keep going"],
      pt: ["JPS(início, destino)", "  A* sobre pontos de salto: aberto ← {início}", "  retira o ponto de salto de menor g + h; se é o destino, reconstrói o caminho", "  para cada direção permitida: ponto ← SALTA(atual, direção)", "    se ponto existe e g(atual) + distância < g(ponto): atualiza, insere ponto", "SALTA(célula, direção): dá um passo; para numa parede (nada), no destino ou numa curva forçada (ponto de salto); num trecho vertical tenta também os dois saltos laterais; senão continua"],
    },
  },

  thetaStar: {
    ...SIZE,
    slug: "theta-star",
    name: "Theta*",
    subtitle: { en: "any-angle A* · parents by line of sight", pt: "A* de qualquer ângulo · pais por linha de visão" },
    tagline: { en: "Theta* · paths that cut across the grid instead of hugging it", pt: "Theta* · caminhos que cortam a grade em vez de seguir suas linhas" },
    legend: LEGEND,
    kpis: [KPI_EXPANDED, { key: "open", label: { en: "OPEN SET", pt: "ABERTO" }, sub: { en: "candidates in the heap", pt: "candidatas no heap" } }, { key: "shortcuts", label: { en: "SHORTCUTS", pt: "ATALHOS" }, sub: { en: "links straight to a grandparent", pt: "ligações diretas a um avô" } }, { key: "relaxations", label: { en: "RELAXED", pt: "RELAXADAS" }, sub: { en: "distances improved", pt: "distâncias melhoradas" } }, KPI_PATH],
    idea: {
      en: [
        "A* on a grid returns paths made of grid moves, so a diagonal crossing of open ground becomes a staircase up to 41% longer than the straight line. Theta* fixes that in one place: when it relaxes a neighbour, it first checks whether the neighbour can see the current cell's parent in a straight line, and if so links it straight to that parent instead.",
        "Paths become sequences of a few waypoints joined by straight segments, with Euclidean lengths, while the search itself is still A* over the same cells. It is not guaranteed optimal among all any-angle paths, but it is within a percent or two of the true shortest in practice.",
      ],
      pt: [
        "O A* numa grade devolve caminhos feitos de movimentos da grade, então uma travessia diagonal de terreno aberto vira uma escada até 41% mais longa que a linha reta. O Theta* conserta isso num único lugar: ao relaxar um vizinho, checa antes se o vizinho enxerga em linha reta o pai da célula atual, e se sim liga direto nesse pai.",
        "Os caminhos viram sequências de poucos pontos ligados por segmentos retos, com comprimentos euclidianos, enquanto a busca em si continua sendo o A* sobre as mesmas células. Não é garantidamente ótimo entre todos os caminhos de qualquer ângulo, mas fica a um ou dois por cento do mínimo real na prática.",
      ],
    },
    stages: [["primary", { en: "pop", pt: "retira" }, { en: "lowest distance + straight line to the goal", pt: "menor distância + linha reta ao destino" }], ["violet", { en: "line of sight", pt: "linha de visão" }, { en: "can the neighbour see the current cell's parent?", pt: "o vizinho enxerga o pai da célula atual?" }], ["swap", { en: "relax", pt: "relaxa" }, { en: "link to the grandparent if visible, else to the current cell", pt: "liga ao avô se visível, senão à célula atual" }], STAGE_PATH],
    complexity: [
      [{ en: "best", pt: "melhor" }, "O(d)", "green", { en: "the goal is visible from the start", pt: "o destino é visível do início" }],
      [{ en: "average", pt: "médio" }, "O(E log V · L)", "text", { en: "A* plus a line-of-sight check of length L per relaxation", pt: "A* mais uma checagem de linha de visão de comprimento L por relaxamento" }],
      [{ en: "worst", pt: "pior" }, "O(E log V · L)", "text", { en: "long sight lines on an open map", pt: "linhas de visão longas num mapa aberto" }],
      [{ en: "space", pt: "espaço" }, "O(V)", "text", { en: "same as A*", pt: "o mesmo do A*" }],
    ],
    chartTitle: { en: "PATH LENGTH · 44×20 OPEN FIELD, DIAGONAL CROSSING", pt: "COMPRIMENTO DO CAMINHO · CAMPO ABERTO 44×20, TRAVESSIA DIAGONAL" },
    chart: [["theta*", 48, true], ["straight line", 47], ["a* 8-way", 52], ["a* 4-way", 62], ["dfs", 141]],
    chartNote: { en: "the 4-way staircase is 30% longer than the straight line Theta* nearly matches", pt: "a escada de 4 direções é 30% mais longa que a linha reta que o Theta* quase iguala" },
    when: {
      en: ["Units that move freely in the world but plan on a grid: games, drones, robots with a smooth controller.", "Whenever the staircase path of A* looks wrong on screen and a post-smoothing pass is not enough."],
      pt: ["Unidades que se movem livremente no mundo mas planejam numa grade: jogos, drones, robôs com controlador suave.", "Sempre que o caminho em escada do A* fica estranho na tela e um pós-suavizamento não basta."],
    },
    pitfalls: {
      en: ["The line-of-sight test must cover every cell the segment touches; a corner-cutting test lets paths clip walls.", "Each relaxation pays a line-of-sight check, so Theta* is slower per expansion than A*; Lazy Theta* defers the check to the pop.", "The heuristic must be Euclidean, not Manhattan, or the any-angle costs are overestimated."],
      pt: ["O teste de linha de visão precisa cobrir toda célula que o segmento toca; um teste que corta quinas deixa o caminho raspar paredes.", "Cada relaxamento paga uma checagem de linha de visão, então o Theta* é mais lento por expansão que o A*; o Lazy Theta* adia a checagem para a retirada.", "A heurística precisa ser euclidiana, não Manhattan, ou os custos de qualquer ângulo são superestimados."],
    },
    history: {
      en: "Alex Nash, Kenny Daniel, Sven Koenig and Ariel Felner introduced Theta* in 2007 as the first any-angle search that runs at A* speed; Lazy Theta* followed in 2010. Anya, from 2013, finally gave an optimal any-angle algorithm, at the cost of a more complex search space.",
      pt: "Alex Nash, Kenny Daniel, Sven Koenig e Ariel Felner introduziram o Theta* em 2007 como a primeira busca de qualquer ângulo na velocidade do A*; o Lazy Theta* veio em 2010. O Anya, de 2013, finalmente deu um algoritmo ótimo de qualquer ângulo, ao custo de um espaço de busca mais complexo.",
    },
    file: "theta_star",
    code: {
      ts: ["function thetaStar(grid: Grid, start: Cell, goal: Cell) {", "  const open = new MinHeap<Cell>([start]), distance = new Map([[start, 0]]), parent = new Map([[start, start]]);", "  while (open.size > 0) {", "    const current = open.pop(); // lowest distance + straight line to the goal", "    if (current === goal) return rebuild(parent, current);", "    for (const neighbor of neighbors(grid, current)) {", "      const grandparent = parent.get(current)!;", "      const via = lineOfSight(grid, grandparent, neighbor) ? grandparent : current;", "      const candidate = distance.get(via)! + euclid(via, neighbor);", "      if (candidate >= (distance.get(neighbor) ?? Infinity)) continue;", "      distance.set(neighbor, candidate); parent.set(neighbor, via);", "      open.push(neighbor, candidate + euclid(neighbor, goal));", "    }", "  }", "}"],
      py: ["def theta_star(grid, start, goal):", "    open_set = [(0, start)]; distance = {start: 0}; parent = {start: start}", "    while open_set:", "        _, current = heapq.heappop(open_set)  # lowest distance + straight line to the goal", "        if current == goal: return rebuild(parent, current)", "        for neighbor in neighbors(grid, current):", "            grandparent = parent[current]", "            via = grandparent if line_of_sight(grid, grandparent, neighbor) else current", "            candidate = distance[via] + euclid(via, neighbor)", "            if candidate >= distance.get(neighbor, math.inf): continue", "            distance[neighbor] = candidate; parent[neighbor] = via", "            heapq.heappush(open_set, (candidate + euclid(neighbor, goal), neighbor))", "", "", ""],
      java: ["List<Cell> thetaStar(Grid grid, Cell start, Cell goal) {", "  PriorityQueue<Cell> open = new PriorityQueue<>(byScore); open.add(start); Map<Cell,Double> distance = new HashMap<>(Map.of(start, 0.0)); Map<Cell,Cell> parent = new HashMap<>(Map.of(start, start));", "  while (!open.isEmpty()) {", "    Cell current = open.poll(); // lowest distance + straight line to the goal", "    if (current.equals(goal)) return rebuild(parent, current);", "    for (Cell neighbor : neighbors(grid, current)) {", "      Cell grandparent = parent.get(current);", "      Cell via = lineOfSight(grid, grandparent, neighbor) ? grandparent : current;", "      double candidate = distance.get(via) + euclid(via, neighbor);", "      if (candidate >= distance.getOrDefault(neighbor, Double.MAX_VALUE)) continue;", "      distance.put(neighbor, candidate); parent.put(neighbor, via);", "      neighbor.score = candidate + euclid(neighbor, goal); open.add(neighbor);", "    }", "  }", "}"],
      cpp: ["std::vector<Cell> thetaStar(const Grid& grid, Cell start, Cell goal) {", "  std::priority_queue<Node, std::vector<Node>, ByScore> open; open.push({start, 0}); std::unordered_map<Cell,double> distance{{start, 0}}; std::unordered_map<Cell,Cell> parent{{start, start}};", "  while (!open.empty()) {", "    Cell current = open.top().cell; open.pop(); // lowest distance + straight line to the goal", "    if (current == goal) return rebuild(parent, current);", "    for (Cell neighbor : neighbors(grid, current)) {", "      Cell grandparent = parent[current];", "      Cell via = lineOfSight(grid, grandparent, neighbor) ? grandparent : current;", "      double candidate = distance[via] + euclid(via, neighbor);", "      if (distance.count(neighbor) && candidate >= distance[neighbor]) continue;", "      distance[neighbor] = candidate; parent[neighbor] = via;", "      open.push({neighbor, candidate + euclid(neighbor, goal)});", "    }", "  }", "}"],
      c: ["Path theta_star(Grid *grid, Cell start, Cell goal) {", "  Heap open = heap_new(); heap_push(&open, start, 0); double distance[ROWS][COLS]; fill(distance, INFINITY); distance[start.row][start.col] = 0; Cell parent[ROWS][COLS]; parent[start.row][start.col] = start;", "  while (open.size > 0) {", "    Cell current = heap_pop(&open); /* lowest distance + straight line to the goal */", "    if (cell_eq(current, goal)) return rebuild(parent, current);", "    for (int direction = 0; direction < 4; direction++) { Cell neighbor = neighbor_at(grid, current, direction); if (!neighbor.ok) continue;", "      Cell grandparent = parent[current.row][current.col];", "      Cell via = line_of_sight(grid, grandparent, neighbor) ? grandparent : current;", "      double candidate = distance[via.row][via.col] + euclid(via, neighbor);", "      if (candidate >= distance[neighbor.row][neighbor.col]) continue;", "      distance[neighbor.row][neighbor.col] = candidate; parent[neighbor.row][neighbor.col] = via;", "      heap_push(&open, neighbor, candidate + euclid(neighbor, goal));", "    }", "  }", "}"],
      go: ["func thetaStar(grid Grid, start, goal Cell) []Cell {", "\topen := NewMinHeap(); open.Push(start, 0); distance := map[Cell]float64{start: 0}; parent := map[Cell]Cell{start: start}", "\tfor open.Len() > 0 {", "\t\tcurrent := open.Pop() // lowest distance + straight line to the goal", "\t\tif current == goal { return rebuild(parent, current) }", "\t\tfor _, neighbor := range neighbors(grid, current) {", "\t\t\tgrandparent := parent[current]", "\t\t\tvia := current; if lineOfSight(grid, grandparent, neighbor) { via = grandparent }", "\t\t\tcandidate := distance[via] + euclid(via, neighbor)", "\t\t\tif old, ok := distance[neighbor]; ok && candidate >= old { continue }", "\t\t\tdistance[neighbor] = candidate; parent[neighbor] = via", "\t\t\topen.Push(neighbor, candidate+euclid(neighbor, goal))", "\t\t}", "\t}", "\treturn nil }"],
      rs: ["fn theta_star(grid: &Grid, start: Cell, goal: Cell) -> Option<Vec<Cell>> {", "    let mut open = BinaryHeap::from([Reverse((0.0, start))]); let mut distance = HashMap::from([(start, 0.0)]); let mut parent = HashMap::from([(start, start)]);", "    while let Some(Reverse((_, current))) = open.pop() {", "        // popped the lowest distance + straight line to the goal", "        if current == goal { return Some(rebuild(&parent, current)); }", "        for neighbor in grid.neighbors(current) {", "            let grandparent = parent[&current];", "            let via = if line_of_sight(grid, grandparent, neighbor) { grandparent } else { current };", "            let candidate = distance[&via] + euclid(via, neighbor);", "            if candidate >= *distance.get(&neighbor).unwrap_or(&f64::INFINITY) { continue; }", "            distance.insert(neighbor, candidate); parent.insert(neighbor, via);", "            open.push(Reverse((candidate + euclid(neighbor, goal), neighbor)));", "        }", "    }", "    None }"],
    },
    pseudo: {
      en: ["THETA*(start, goal)", "  open ← {start}; dist[start] ← 0; parent[start] ← start", "  while open not empty", "    current ← the open cell with the lowest dist + euclid(current, goal); if it is the goal: rebuild the path", "    for each neighbour of current", "      via ← parent[current] if it can see neighbour in a straight line, else current", "      if dist[via] + euclid(via, neighbour) < dist[neighbour]: update dist, parent[neighbour] ← via, add neighbour to open"],
      pt: ["THETA*(início, destino)", "  aberto ← {início}; dist[início] ← 0; pai[início] ← início", "  enquanto aberto não vazio", "    atual ← a célula aberta de menor dist + euclid(atual, destino); se é o destino: reconstrói o caminho", "    para cada vizinho de atual", "      via ← pai[atual] se enxerga o vizinho em linha reta, senão atual", "      se dist[via] + euclid(via, vizinho) < dist[vizinho]: atualiza dist, pai[vizinho] ← via, adiciona vizinho ao aberto"],
    },
  },
} satisfies Record<string, AlgorithmSpec>;
